spring:
  application:
    name: security-service

  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: Kanybek20065732
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

token:
  signing:
    secret:
      key: ${SECRET_KEY:YXJtd29ybGRwb3JjaGRvb3J0ZWFjaGVyY29hY2hlcXVpcG1lbnRmZWFyc2hha2luZ3dlYWtkdQ==}

access:
  token:
    expiration:
      date: 24

refresh:
  token:
    expiration:
      date: 168

private:
  key:
    path: keys/private_key.pem

public:
  key:
    path: keys/public_key.pem

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 40
    prefer-ip-address: true
